# Generated by Django 3.2.8 on 2021-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211031_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectemployee',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='projectemployee',
            name='start_date',
            field=models.DateField(),
        ),
    ]
