# Generated by Django 3.2.8 on 2021-10-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_code', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=400, null=True)),
                ('active_from', models.DateTimeField(auto_now=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_code', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=400, null=True)),
                ('active_from', models.DateTimeField(auto_now=True)),
                ('active_to', models.DateTimeField(blank=True, null=True)),
                ('vendor_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
